from rest_framework import serializers
from .models import Post, Category, Tag, Comment


class CategorySerializer(serializers.ModelSerializer):
    class Meta:
        model = Category
        fields = ['id', 'name', 'slug']


class TagSerializer(serializers.ModelSerializer):
    class Meta:
        model = Tag
        fields = ['id', 'name', 'slug']


class PostSerializer(serializers.ModelSerializer):
    category = CategorySerializer(read_only=True)
    tags = TagSerializer(many=True, read_only=True)
    author_name = serializers.CharField(source='author.username', read_only=True)

    # Write-only fields for category and tags
    category_id = serializers.IntegerField(write_only=True, required=False, allow_null=True)
    tag_ids = serializers.ListField(
        child=serializers.IntegerField(),
        write_only=True,
        required=False,
        allow_empty=True
    )

    class Meta:
        model = Post
        fields = [
            'id', 'title', 'slug', 'excerpt', 'content', 'featured_image',
            'category', 'category_id',
            'tags', 'tag_ids',
            'author', 'author_name',
            'status', 'published_at', 'created_at', 'updated_at'
        ]
        # CRITICAL: Make slug read-only so it's auto-generated from title
        read_only_fields = ['author', 'published_at', 'slug', 'created_at', 'updated_at']

    def create(self, validated_data):
        category_id = validated_data.pop('category_id', None)
        tag_ids = validated_data.pop('tag_ids', [])
        
        # Create the post - slug will be auto-generated by the model's save()
        post = Post.objects.create(**validated_data)

        # Set category if provided
        if category_id:
            try:
                category = Category.objects.get(id=category_id)
                post.category = category
                post.save()
            except Category.DoesNotExist:
                pass

        # Set tags if provided
        if tag_ids:
            tags = Tag.objects.filter(id__in=tag_ids)
            post.tags.set(tags)

        return post

    def update(self, instance, validated_data):
        category_id = validated_data.pop('category_id', None)
        tag_ids = validated_data.pop('tag_ids', None)

        # Update basic fields
        instance.title = validated_data.get('title', instance.title)
        # The model will auto-generate slug when saving
        instance.excerpt = validated_data.get('excerpt', instance.excerpt)
        instance.content = validated_data.get('content', instance.content)
        instance.featured_image = validated_data.get('featured_image', instance.featured_image)
        instance.status = validated_data.get('status', instance.status)
        instance.save()

        # Update category if provided
        if category_id is not None:
            try:
                category = Category.objects.get(id=category_id)
                instance.category = category
            except Category.DoesNotExist:
                instance.category = None
            instance.save()

        # Update tags if provided
        if tag_ids is not None:
            tags = Tag.objects.filter(id__in=tag_ids)
            instance.tags.set(tags)

        return instance


class CommentSerializer(serializers.ModelSerializer):
    author_name = serializers.CharField(source='author.username', read_only=True)
    post_slug = serializers.CharField(source='post.slug', read_only=True)

    class Meta:
        model = Comment
        fields = [
            'id', 'post', 'post_slug',
            'author', 'author_name',
            'content', 'created_at', 'updated_at', 'is_approved'
        ]
        read_only_fields = ['author', 'is_approved', 'post', 'created_at', 'updated_at']